import { WorkerUser, ProviderUser, EmployerUser, MedicalRecord, AccessLog } from '../types';

export const INITIAL_WORKERS: WorkerUser[] = [
  {
    id: 'usr_tareq_5820',
    role: 'worker',
    health_id: 'MC-5820-1943',
    name: 'Tareq Rahman',
    dob: '1992-04-15',
    gender: 'Male',
    phone: '+65 8123 4567',
    blood_group: 'O+',
    allergies: 'Penicillin, Cephalosporins',
    chronic_conditions: ['Mild Asthma'],
    preferred_language: 'en',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    emergency_contact: 'Brother (Kareem): +65 9182 7364',
    status: 'Fit for Work',
    vaccinated: true,
    vaccine_count: 3,
    recommendations: 'Cleared for high-elevation and heavy construction work. Keep rescue inhaler accessible during high-heat shifts.',
    created_at: '2024-01-10T08:30:00Z',
  },
  {
    id: 'usr_siti_7412',
    role: 'worker',
    health_id: 'MC-7412-8823',
    name: 'Siti Aminah',
    dob: '1995-09-22',
    gender: 'Female',
    phone: '+65 9234 5678',
    blood_group: 'A-',
    allergies: 'Latex',
    chronic_conditions: ['Asthma Condition'],
    preferred_language: 'en',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    emergency_contact: 'Spouse (Farhan): +65 8291 0394',
    status: 'Fit for Work',
    vaccinated: true,
    vaccine_count: 2,
    recommendations: 'Cleared for manufacturing and logistics duties. Latex-free PPE required in cleanroom settings.',
    created_at: '2024-02-14T09:15:00Z',
  },
  {
    id: 'usr_juan_1094',
    role: 'worker',
    health_id: 'MC-1094-3329',
    name: 'Juan Carlos',
    dob: '1988-11-03',
    gender: 'Male',
    phone: '+65 9876 5432',
    blood_group: 'B+',
    allergies: 'Sulfa Drugs, Aspirin',
    chronic_conditions: ['Hypertension (Controlled)'],
    preferred_language: 'es',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    emergency_contact: 'Wife (Maria): +65 9301 8472',
    status: 'Fit for Work',
    vaccinated: true,
    vaccine_count: 3,
    recommendations: 'Annual cardiovascular checkup completed. Regular hydration breaks advised in outdoor roles.',
    created_at: '2024-03-01T11:00:00Z',
  },
];

export const INITIAL_PROVIDERS: ProviderUser[] = [
  {
    id: 'prov_sarah_101',
    name: 'Dr. Sarah Lim',
    facility: 'Central Community Clinic #4',
    reg_no: 'MCR-2018-9482',
    role: 'provider',
    email: 'sarah.lim@communityhealth.sg',
  },
  {
    id: 'prov_david_102',
    name: 'Dr. David Tan',
    facility: 'Jurong Migrant Health Hub',
    reg_no: 'MCR-2015-7731',
    role: 'provider',
    email: 'david.tan@jurongcare.org',
  },
];

export const INITIAL_EMPLOYERS: EmployerUser[] = [
  {
    id: 'emp_apex_001',
    name: 'Apex Infra & Construction Ltd.',
    company: 'Apex Infrastructure Group',
    role: 'employer',
    email: 'safety@apexinfra.com',
  },
];

export const INITIAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec_001',
    worker_id: 'usr_tareq_5820',
    type: 'visit',
    provider_name: 'Dr. Sarah Lim',
    facility_name: 'Central Community Clinic #4',
    notes: 'Routine pre-employment clinical checkup. BP 118/76 mmHg. Resting pulse 72 bpm. Clear lung sounds bilaterally. Declared fit for general construction and physical labor duties.',
    created_at: '2024-04-12T10:15:00Z',
  },
  {
    id: 'rec_002',
    worker_id: 'usr_tareq_5820',
    type: 'vaccination',
    provider_name: 'Nurse Joyce Wong',
    facility_name: 'Central Community Clinic #4',
    notes: 'Administered Tdap (Tetanus, Diphtheria, Pertussis) booster dose, Lot #TD-9481A. Patient monitored 15 mins post-injection with zero immediate adverse reaction.',
    created_at: '2024-04-12T10:30:00Z',
  },
  {
    id: 'rec_003',
    worker_id: 'usr_tareq_5820',
    type: 'prescription',
    provider_name: 'Dr. Sarah Lim',
    facility_name: 'Central Community Clinic #4',
    notes: 'Salbutamol Inhaler 100mcg (1-2 puffs PRN for mild chest tightness or dust exposure). Caution: Patient has severe Penicillin allergy.',
    created_at: '2024-05-18T14:20:00Z',
  },
  {
    id: 'rec_004',
    worker_id: 'usr_tareq_5820',
    type: 'lab_result',
    provider_name: 'Quest Diagnostics Regional Lab',
    facility_name: 'Jurong Health Laboratory',
    notes: 'Complete Blood Count (CBC) & Fasting Lipid Panel: Hemoglobin 14.8 g/dL (Normal), Fasting Glucose 92 mg/dL (Normal). No signs of infection.',
    created_at: '2024-06-02T09:00:00Z',
  },
  {
    id: 'rec_005',
    worker_id: 'usr_siti_7412',
    type: 'visit',
    provider_name: 'Dr. David Tan',
    facility_name: 'Jurong Migrant Health Hub',
    notes: 'Annual occupational health fitness exam. Peak flow 410 L/min. Hearing test Normal. Fit for factory floor operations.',
    created_at: '2024-05-10T11:30:00Z',
  },
  {
    id: 'rec_006',
    worker_id: 'usr_juan_1094',
    type: 'prescription',
    provider_name: 'Dr. Sarah Lim',
    facility_name: 'Central Community Clinic #4',
    notes: 'Amlodipine 5mg OD (morning dose for blood pressure maintenance). Advised 2L daily water intake on work sites.',
    created_at: '2024-06-15T16:00:00Z',
  },
];

export const INITIAL_LOGS: AccessLog[] = [
  {
    id: 'log_001',
    worker_id: 'usr_tareq_5820',
    viewer_name: 'Dr. Sarah Lim',
    viewer_role: 'Doctor / Clinic Staff',
    facility: 'Central Community Clinic #4',
    access_type: 'Full Record View & Update (5-min consent approved)',
    timestamp: '2024-04-12T10:14:22Z',
  },
  {
    id: 'log_002',
    worker_id: 'usr_tareq_5820',
    viewer_name: 'Apex Infrastructure Safety Officer',
    viewer_role: 'Employer Verification',
    facility: 'Site #12 Tuas Depot',
    access_type: 'Fitness Pass Clearance Check (Anonymized summary only)',
    timestamp: '2024-05-01T07:45:10Z',
  },
  {
    id: 'log_003',
    worker_id: 'usr_tareq_5820',
    viewer_name: 'Dr. Sarah Lim',
    viewer_role: 'Doctor / Clinic Staff',
    facility: 'Central Community Clinic #4',
    access_type: 'Rx Update (5-min consent approved)',
    timestamp: '2024-05-18T14:19:05Z',
  },
];
